// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	public "ucenter/internal/handler/public"
	"ucenter/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取微信登录二维码
				Method:  http.MethodPost,
				Path:    "/api/v1/public/login",
				Handler: public.WechatLoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 微信消息回调消息与验证
				Method:  http.MethodPost,
				Path:    "/api/v1/noauth/wechat/notify",
				Handler: public.WechatMessageNotifyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/noauth/wechat/vertify",
				Handler: public.WechatMessageVertifyHandler(serverCtx),
			},
		},
	)
}
