// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	qrcode "ucenter/src/internal/handler/qrcode"
	"ucenter/src/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取微信登录二维码
				Method:  http.MethodPost,
				Path:    "/api/v1/noauth/login",
				Handler: qrcode.QrcodeLoginHandler(serverCtx),
			},
		},
	)
}
